injectEnvironmentFiles:
  - .env.local-mnapp-fap?

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: ${FONTAWESOME_PACKAGE_TOKEN}
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: ${FONTAWESOME_PACKAGE_TOKEN}

packageExtensions:
  '@firebase/auth@*':
    dependencies:
      '@firebase/app': '*'
